// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvpmdqaurtfjngngfdga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2cG1kcWF1cnRmam5nbmdmZGdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMjQ2OTIsImV4cCI6MjA3MjYwMDY5Mn0.cA31dPHx4BIsdUpx4051S5pK8K_QB4iU5DRhVwna8Bo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});